#+BEGIN_SRC html
layout: post
title: 5個問題，讓你做自己的生涯設計師 
date: 2018-07-31 02:00:00
tags: [阿德勒]
author: 陳璿丞
description: 
#+END_SRC


** 熱情與天賦
因為最近在準備報告，加上自己還有生活周圍的朋友，開始對自己的人生有疑問？或是對於自己的未來感到迷惘。迷惘的東西很多，但有很大一部分是，我以後要做什麼？我想要成為一個怎麼樣的人？有很大一部分是關係到職業，或是說生涯規畫。坊間也有很多的成長課程、也還有很多的「尋找熱情與天賦」的論壇，但是這有很多東西是要問你自己，而非問他人。

另外，還有一點，為了因應21世紀的快速變動，以前工業時代，我們對於一份工作可以做到老死，但現在因為技術一再更新，能有一份工作穩定做到退休的越來越少，我們需要的不再只是以前製式的量表評估，寫一寫選擇題，知道自己的個性是什麼，就可以依照專家給的意見，選定職業。現在許多高中大學的輔導室提供的興趣量表、或是未來生涯規畫，可能都變成了廢紙。或是成年以後，對於“我到底要做什麼？”，我的天命是什麼？這類的人生大問題，除了求神拜佛，還有沒有其他的方式？

** 阿德勒又來啦
好吧，其實不是阿德勒，因為在一百多年前，他出生的年代，並沒有這樣一個人的生涯會有大量變動的可能性；而是後來有學者Mark L. Savickas提出的一些方式；他也用了這設計的量表，做了很多的實驗和探詢，他建立了五個問句，讓心理師可以和個案討論，一起找出如何，面對自己的性格，找出人生的航道，成為自己的航海王。
*** 這不是指引，而是談論
很多生涯規劃，無論是課程或是現行的講座，有很多一部分是有個明師、明燈、量表，去指引你要往何方走、要去哪裡；但是這裡提到的更多是如何和治療師做進一步的討論、和從自己的敘述裡，看出自己的可能性。這一開始是設計給治療師來和案主討論的一系列問題；但後來也有出「my career story」的自填的敘述探索（之後有機會再提）不過整體來看，問句的方式是雷同的。

** 生涯建構訪談（career construction interview, CCI）
這是由Savickas所建構的五個問句：
- 關於你的英雄
- 你喜愛看的電視、雜誌、網站
- 最愛的故事
- 最喜歡的格言
- 早期回憶

*** 你的英雄
#+BEGIN_QUOTE
在你成長的過程中，誰是你最佩服的人？誰是你的英雄？我想要知道，在你小的時候，除了你爸媽之外，你最佩服的三個人。
這3個人，可以是你喜歡的卡通人物、你認識或不認識的、可以是書本或是電視電影的角色。
#+END_QUOTE
tips:
- 小的時候，越早越好，儘量不要晚於國中
- 要注意這些人的特質和描述、注意形容詞
- 這些英雄們有什麼共同的特點
- 有什麼不一樣的？

*** 喜歡的電視、雜誌、網站
#+BEGIN_QUOTE
- 你平常有訂閱什麼雜誌或是會定期看雜誌嗎？
  - 你為什麼覺得它有趣
  - 是什麼吸引你 
#+END_QUOTE

同樣的，電視劇也是這樣問，還有網站也是。因為現在有很多電子雜誌或是rss、medium、部落格等電子雜誌的類型取代了雜誌的功能。也可以詢問。

*** 最喜歡的故事
#+BEGIN_QUOTE
最近，你最喜歡的小說或是電影故事是什麼？跟我說說看故事的內容
#+END_QUOTE

*** 最愛的格言
#+BEGIN_QUOTE
你最喜歡的格言是什麼?
#+END_QUOTE

如果個案想不起來，

#+BEGIN_QUOTE
你最近有沒有從什麼電影海報，或是書本中看到什麼短言你很喜歡的？
你自己生活周遭有沒有貼什麼勵志小語？
#+END_QUOTE

*** 早期回憶
#+BEGIN_QUOTE
- 你可以想得起最早的回憶是什麼？我想要聽聽看你想得起來的三個故事。
- 如果你可以為這三個記憶標訂情緒的話，你會貼上什麼情緒字眼？
- 如果你可以為這三個記憶拍一張照片，可以跟我說說，這照片看起來是什麼樣子嗎？
- 可以替這三個記憶，各下一個標題嗎？就像報紙一下
#+END_QUOTE
tips:
- 如果個案想得起來3~6歲是最好的，如果不行最好是12歲前
- 標題內要有動詞

** 生涯速描

